piVersion: apps/v1
kind: Deployment
metadata:
  name: php1
  labels:
    app: php1
spec:
  selector:
    matchLabels:
      app: php1
  replicas: 1
  template:
    metadata:
      labels:
        app: php1
    spec:
      containers:
        - name: php1
          image: 616749751767.dkr.ecr.ap-northeast-1.amazonaws.com/dev-image:latest
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 80
