apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-pod
    pod-template-hash: 84dfbcb48d
  name: nginx-svc
  namespace: sock-shop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-pod
    pod-template-hash: 84dfbcb48d
  type: LoadBalancer
status:
  loadBalancer: {}
