apiVersion: v1
kind: Service
metadata:
  name: php1
  labels:
    app: php1
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: php1

