apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: "queue-port"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
    - name: "gui-port"
      protocol: "TCP"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq

